version: '3.9'

services:
  postgres:
    image: postgres
    ports:
      - 5481:5432
    volumes:
      - /home/gsakshi/Desktop/docker23/pgReplication23/pgData23:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=1258