version: "3"

services:

  node23:
    build: .                            # . means, it takes Dockerfile present in currentPath
    # image: gopal612/level2b:v1        # use either build (oR) image only one of them
    depends_on:
      - postgres
    ports:
      - "18090:18090"
      # - "12201:12201/udp"
    command: npm run dev

    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "1k" 
    # logging:
    #   driver: gelf
    #   options:
    #     # gelf-address: udp://127.0.0.1:12201
    #     gelf-address: docker.host.internal:12201
    #     tag: "node23_gelf23"
    #     gelf-compression-type: none

  # postgres45:       # why its not working with postgres45, but why its working with postgres46
  #   image: postgres:15
  #     # collation version mismatch ===>  # REBUILD DATABASE db87; # ALTER DATABASE db87 REFRESH COLLATION VERSION;
  #   ports:
  #     - "35432:5432"
  #   environment:
  #     POSTGRES_USER: postgres
  #     # POSTGRES_PASSWORD: /run/secrets/passwd23          # db password will be a string === "/run/secrets/passwd23"
  #     # POSTGRES_PASSWORD_FILE: /run/secrets/passwd23
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: postgres
  #   # volumes:
  #   #   - /var/lib/postgresql/data
  #   secrets:
  #     - passwd23

secrets:
  passwd23:
    file: secret23.txt
# volumes:
#   america23:
#     driver: local
#     driver_opts:
#       o: bind
#       device: $PWD