global:
  scrape_interval: 10s

scrape_configs:
- job_name: 'node2323'
  static_configs:
  - targets: ['10.0.54.240:3033']
  metrics_path: '/prom23/metrics'

remote_write:
- url: "http://localhost:30012"
  # basic_auth:
  #   username: <your user name>
  #   password: <Your Grafana.com API Key>