version: '3'

services:
  jenkins:
    container_name: jenkins24
    image: jenkins/jenkins:lts
    ports:
      - "18080:8080"
    privileged: true
    user: root
    volumes:
      - ./jenkinsData24:/var/jenkins_home