services:

  pg_master23:
    image: postgres:15
    ports:
      - 15541:5432
    volumes:
      - ./pgReplCommonData23:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data
      - POSTGRESQL_REPLICATION_MODE=${MASTER_REPLICATION_MODE}
      - PG_REP_USER=${DB_REPLICATION_USER}
      - PG_REP_PASSWORD=${DB_REPLICATION_PASSWORD}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}

  pg_slave31:
    image: postgres:15
    volumes:
      - ./pgReplCommonData23:/var/lib/postgresql/data
    ports:
      - 15546:5432
    depends_on:
      - pg_master23
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data
      - POSTGRESQL_REPLICATION_MODE=${SLAVE_REPLICATION_MODE}
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1258
      - PG_REP_USER=${DB_REPLICATION_USER}
      - PG_REP_PASSWORD=${DB_REPLICATION_PASSWORD}
      - PG_MASTER_HOST=${MASTER_HOST}
      - PG_MASTER_PORT=${MASTER_PORT}
  
